### ISSUE TITLE
[FEATURE-REQUEST] Support nested Hocker files

### ISSUE THREAD

**Issue by MartinSeeler** [knutwalker/hocker#1]
It would be really nice to use / import Hocker files from other folders to build dependencies, something like this:

``` yaml
backend:
    import: ./backend
frontend:
    import: ./frontend
    link: backend
```
